version: '3.8'
services:
  apigateway:
    build: .
    command: bash -c "flask db upgrade && python wsgi.py"
    ports:
      - "5000:8181"
    depends_on:
      - db
      - redis
  db:
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gateway
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/db:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"